// GENERATED by scripts/sync-shared.mjs from packages/core/src — do not edit.
/**
 * "What should I fill here?" (PLAYBOOK Task 10.4): a plain-words explanation
 * of one field, the value Filler would use, any risk, and where the
 * explanation came from. Works with no AI at all (rules, memory, policy);
 * an AI classification or a vision reading only adds to it.
 */
import { formatForField, type FactLookup } from '../mapper/format.ts';
import type { MapResult } from '../mapper/map.ts';
import { classifyRisk, type DeniedCategory, type Policy } from '../policy/deny.ts';
import { getKeyDef } from '../schema/keys.ts';
import type { FieldDescriptor } from '../schema/records.ts';

export type ExplanationSource = 'policy' | 'rules' | 'memory' | 'ai' | 'vision' | 'page';

export interface Explanation {
  fieldId: string;
  label: string;
  summary: string;
  /** The value Filler would put in, when it has one, and its vault key. */
  value?: string;
  key?: string;
  risk?: string;
  source: ExplanationSource;
  sourceLabel: string;
}

export const SOURCE_LABELS: Record<ExplanationSource, string> = {
  policy: "Filler's never-fill rules",
  rules: "Filler's rules (the field's label and markup)",
  memory: 'Remembered from your earlier answer on this site',
  ai: "Filler's AI (from the field's text only)",
  vision: "Filler's AI (read from the screen)",
  page: "The page's own text",
};

const DENIED_WHAT: Record<DeniedCategory, string> = {
  password: 'a password',
  otp: 'a one-time code',
  card_number: 'a card number',
  card_security_code: 'a card security code (CVV)',
  card_expiry: 'a card expiry date',
  bank_account: 'bank account details',
  upi_pin: 'a UPI or ATM PIN',
  passport: 'your passport number',
  aadhaar: 'your Aadhaar number',
  pan: 'your PAN',
  ssn: 'a Social Security number',
  government_id: 'a government ID number',
  security_question: 'a security question',
  captcha: 'a CAPTCHA',
  user_rule: 'something you told Filler never to fill',
};

const keyName = (key: string) =>
  (getKeyDef(key)?.label ?? key.replace(/^custom\./, '').replace(/_/g, ' ')).toLowerCase();

export function explainField(
  field: FieldDescriptor,
  mapping: MapResult | undefined,
  lookup: FactLookup,
  options: {
    policy?: Pick<Policy, 'classifyRisk'>;
    source?: 'ai' | 'vision';
    aiReason?: string;
  } = {},
): Explanation {
  const base = { fieldId: field.id, label: field.label || 'This field' };
  const make = (e: Omit<Explanation, 'fieldId' | 'label' | 'sourceLabel'>): Explanation => ({
    ...base,
    ...e,
    sourceLabel: SOURCE_LABELS[e.source],
  });

  const risk = (options.policy ?? { classifyRisk }).classifyRisk(field);
  if (!risk.allowed)
    return make({
      summary: `This asks for ${DENIED_WHAT[risk.category]}, which Filler won't fill.`,
      risk: risk.reason,
      source: 'policy',
    });

  const from: ExplanationSource =
    options.source ??
    (mapping?.source === 'memory'
      ? 'memory'
      : mapping?.source === 'ai'
        ? 'ai'
        : mapping
          ? 'rules'
          : 'page');
  const why = options.aiReason ? ` ${options.aiReason.replace(/\.?$/, '.')}` : '';

  if (!mapping || (mapping.source === 'none' && mapping.kind === 'fact' && !options.aiReason)) {
    const help = field.helpText ? ` It adds: “${field.helpText.slice(0, 160)}”.` : '';
    return make({
      summary: `Filler isn't sure what this asks. The page calls it “${base.label}”.${help}`,
      source: 'page',
    });
  }
  if (mapping.kind === 'skip')
    return make({ summary: `${mapping.reason}${why}`.trim(), source: from });
  if (mapping.kind === 'open_ended' && !mapping.canonicalKey)
    return make({
      summary: `This needs a written answer in your own words${field.maxLength ? ` (up to ${field.maxLength.toLocaleString('en-IN')} characters)` : ''}.${why} Filler can draft it from your details when AI is on.`,
      source: from,
    });
  if (mapping.kind === 'choice' && !mapping.canonicalKey) {
    const opts = (field.options ?? []).map((o) => o.text).filter(Boolean);
    return make({
      summary: `This asks you to choose${opts.length ? ` one of: ${opts.slice(0, 6).join(', ')}${opts.length > 6 ? '…' : ''}` : ' an option'}. That is your decision.${why}`,
      source: from,
    });
  }
  if (!mapping.canonicalKey)
    return make({ summary: `This asks for a detail Filler doesn't have yet.${why}`, source: from });

  const what = keyName(mapping.canonicalKey);
  const formatted = formatForField(field, mapping, lookup);
  if (formatted.ok)
    return make({
      summary: `This asks for your ${what}.${why}`,
      value: Array.isArray(formatted.value) ? formatted.value.join(', ') : formatted.value,
      key: mapping.canonicalKey,
      source: from,
    });
  return make({
    summary: `This asks for your ${what}. ${formatted.reason}${why}`,
    source: from,
  });
}
