// GENERATED by scripts/sync-shared.mjs from packages/core/src — do not edit.
/**
 * The AI seam (PLAYBOOK Task 5.4). Phase 8/9 plug real implementations in;
 * until then — and whenever AI is unavailable — `offlineAi` answers every
 * request with "ask the user", so the deterministic product always works.
 */
import { questionFor } from '../mapper/format.ts';
import type { MapResult } from '../mapper/map.ts';
import type { FactValue, FieldDescriptor, Goal } from '../schema/records.ts';

export interface AiContext {
  goal?: Goal;
  site: string;
  /** Values already used in this session, keyed by canonical key, for consistency. */
  filled: Readonly<Record<string, FactValue>>;
}

export type GeneratedAnswer =
  | { value: string; reason: string; alternatives?: string[] }
  | { needsInput: string; reason: string };

export interface AiSeam {
  /** Which mode answered; shown in the UI so the user always knows. */
  readonly mode: 'offline' | 'ai';
  /** Classifies fields the rules could not (Phase 8). Missing entries stay unmapped. */
  resolveUnmapped(fields: FieldDescriptor[], ctx: AiContext): Promise<Map<string, MapResult>>;
  /** Drafts an answer for an open-ended field (Phase 9). */
  generateAnswer(
    field: FieldDescriptor,
    mapping: MapResult,
    ctx: AiContext,
  ): Promise<GeneratedAnswer>;
}

export const offlineAi: AiSeam = {
  mode: 'offline',
  async resolveUnmapped() {
    return new Map();
  },
  async generateAnswer(field) {
    return {
      needsInput: questionFor(field),
      reason: 'Offline mode: Filler needs you to write this one.',
    };
  },
};
