// GENERATED by scripts/sync-shared.mjs from packages/core/src — do not edit.
/**
 * Plan building: mapping + vault (+ AI seam) → one PlanItem per field.
 * Pure apart from the injected lookups, so it runs anywhere (extension,
 * Android, tests).
 */
import { formatForField, questionFor, type FactLookup } from '../mapper/format.ts';
import type { MapResult } from '../mapper/map.ts';
import { getKeyDef, parseKey } from '../schema/keys.ts';
import type { Fact, FieldDescriptor, PlanItem } from '../schema/records.ts';
import type { AiContext, AiSeam } from './ai.ts';
import { selectFacts } from './select.ts';

export interface PastAnswer {
  value: string;
  platform?: string;
}

export interface PlanDeps {
  lookup: FactLookup;
  ai: AiSeam;
  aiContext: AiContext;
  /** All vault facts, for choosing what an AI draft may use (Phase 9). */
  facts?: readonly Fact[];
  /** Best previously approved answer to a similar question, if any (Task 9.5). */
  pastAnswer?: (field: FieldDescriptor) => PastAnswer | undefined;
}

/** Facts that are really a pitch (written for the goal) can be drafted when the vault lacks them. */
export const DRAFTABLE_GROUPS = new Set(['bio']);

function draftFor(field: FieldDescriptor, deps: PlanDeps): Pick<PlanItem, 'draft'> {
  if (!deps.facts) return {};
  const { groups } = selectFacts(field, deps.facts, deps.aiContext.goal);
  return { draft: { groups } };
}

const hasValue = (v: FieldDescriptor['currentValue']) =>
  Array.isArray(v) ? v.length > 0 : Boolean(v?.trim());
const keyLabel = (key: string) =>
  getKeyDef(key)?.label ?? key.replace(/^custom\./, '').replace(/_/g, ' ');

export async function planField(
  field: FieldDescriptor,
  mapping: MapResult,
  deps: PlanDeps,
): Promise<PlanItem> {
  const base = {
    fieldId: field.id,
    kind: mapping.kind,
    ...(mapping.canonicalKey ? { canonicalKey: mapping.canonicalKey } : {}),
  };

  if (mapping.kind === 'denied' || mapping.kind === 'skip') {
    return { ...base, confidence: mapping.confidence, status: 'skipped', reason: mapping.reason };
  }

  if (mapping.canonicalKey) {
    const formatted = formatForField(field, mapping, deps.lookup);
    if (formatted.ok) {
      const from = mapping.source === 'memory' ? 'memory' : 'vault';
      const reason = `From your vault: ${keyLabel(mapping.canonicalKey)}${formatted.note ? ` (${formatted.note.toLowerCase()})` : ''}`;
      return {
        ...base,
        value: formatted.value,
        source: from,
        confidence: mapping.confidence,
        status: 'pending',
        reason,
      };
    }
    if (mapping.kind !== 'open_ended') {
      const group = parseKey(mapping.canonicalKey)?.group ?? '';
      return {
        ...base,
        confidence: 0,
        status: 'pending',
        reason: formatted.reason,
        // The AI's phrasing ("What is your team called?") beats the generic one.
        question: mapping.question ?? formatted.question,
        ...(DRAFTABLE_GROUPS.has(group) ? draftFor(field, deps) : {}),
      };
    }
  }

  if (mapping.kind === 'open_ended') {
    // Drafting is the user's call (they see which facts would be sent first), so
    // nothing is generated here. Offline, an earlier approved answer is offered.
    const draft = draftFor(field, deps);
    const past = hasValue(field.currentValue) ? undefined : deps.pastAnswer?.(field);
    if (past) {
      return {
        ...base,
        value: past.value,
        source: 'user',
        confidence: 0.6,
        status: 'pending',
        reason: `Your earlier answer to a similar question${past.platform ? ` (${past.platform})` : ''}. Check it fits before approving.`,
        ...draft,
      };
    }
    return {
      ...base,
      confidence: 0,
      status: 'pending',
      reason:
        deps.ai.mode === 'ai'
          ? 'Filler can draft this from your details, or you can write it.'
          : 'Offline mode: Filler needs you to write this one.',
      question: mapping.question ?? questionFor(field),
      ...draft,
    };
  }

  // Unknown fact or a choice with no saved answer: ask, unless the page already has a value.
  if (hasValue(field.currentValue)) {
    return { ...base, confidence: 1, status: 'skipped', reason: 'Already answered on the page.' };
  }
  return {
    ...base,
    confidence: 0,
    status: 'pending',
    reason: mapping.reason,
    question: mapping.question ?? questionFor(field),
  };
}

/** Plans many fields (in order). */
export async function buildPlan(
  fields: FieldDescriptor[],
  mappings: ReadonlyMap<string, MapResult>,
  deps: PlanDeps,
): Promise<PlanItem[]> {
  const items: PlanItem[] = [];
  for (const field of fields) {
    const mapping = mappings.get(field.id);
    if (mapping) items.push(await planField(field, mapping, deps));
  }
  return items;
}
