// GENERATED by scripts/sync-shared.mjs from packages/core/src — do not edit.
/**
 * Plan building: mapping + vault (+ AI seam) → one PlanItem per field.
 * Pure apart from the injected lookups, so it runs anywhere (extension,
 * Android, tests).
 */
import { formatForField, questionFor, type FactLookup } from '../mapper/format.ts';
import type { MapResult } from '../mapper/map.ts';
import { getKeyDef } from '../schema/keys.ts';
import type { FieldDescriptor, PlanItem } from '../schema/records.ts';
import type { AiContext, AiSeam } from './ai.ts';

export interface PlanDeps {
  lookup: FactLookup;
  ai: AiSeam;
  aiContext: AiContext;
}

const hasValue = (v: FieldDescriptor['currentValue']) =>
  Array.isArray(v) ? v.length > 0 : Boolean(v?.trim());
const keyLabel = (key: string) =>
  getKeyDef(key)?.label ?? key.replace(/^custom\./, '').replace(/_/g, ' ');

export async function planField(
  field: FieldDescriptor,
  mapping: MapResult,
  deps: PlanDeps,
): Promise<PlanItem> {
  const base = {
    fieldId: field.id,
    kind: mapping.kind,
    ...(mapping.canonicalKey ? { canonicalKey: mapping.canonicalKey } : {}),
  };

  if (mapping.kind === 'denied' || mapping.kind === 'skip') {
    return { ...base, confidence: mapping.confidence, status: 'skipped', reason: mapping.reason };
  }

  if (mapping.canonicalKey) {
    const formatted = formatForField(field, mapping, deps.lookup);
    if (formatted.ok) {
      const from = mapping.source === 'memory' ? 'memory' : 'vault';
      const reason = `From your vault: ${keyLabel(mapping.canonicalKey)}${formatted.note ? ` (${formatted.note.toLowerCase()})` : ''}`;
      return {
        ...base,
        value: formatted.value,
        source: from,
        confidence: mapping.confidence,
        status: 'pending',
        reason,
      };
    }
    if (mapping.kind !== 'open_ended') {
      return {
        ...base,
        confidence: 0,
        status: 'pending',
        reason: formatted.reason,
        question: formatted.question,
      };
    }
  }

  if (mapping.kind === 'open_ended') {
    const answer = await deps.ai.generateAnswer(field, mapping, deps.aiContext);
    if ('value' in answer) {
      return {
        ...base,
        value: answer.value,
        source: 'ai',
        confidence: 0.5,
        status: 'pending',
        reason: answer.reason,
      };
    }
    return {
      ...base,
      confidence: 0,
      status: 'pending',
      reason: answer.reason,
      question: answer.needsInput,
    };
  }

  // Unknown fact or a choice with no saved answer: ask, unless the page already has a value.
  if (hasValue(field.currentValue)) {
    return { ...base, confidence: 1, status: 'skipped', reason: 'Already answered on the page.' };
  }
  return {
    ...base,
    confidence: 0,
    status: 'pending',
    reason: mapping.reason,
    question: questionFor(field),
  };
}

/** Plans many fields (in order). */
export async function buildPlan(
  fields: FieldDescriptor[],
  mappings: ReadonlyMap<string, MapResult>,
  deps: PlanDeps,
): Promise<PlanItem[]> {
  const items: PlanItem[] = [];
  for (const field of fields) {
    const mapping = mappings.get(field.id);
    if (mapping) items.push(await planField(field, mapping, deps));
  }
  return items;
}
