// GENERATED by scripts/sync-shared.mjs from packages/core/src — do not edit.
/** Loads and compiles the keyword dictionary (`config/field-dictionary.json`). */
import { z } from 'zod';
import { KEY_REGISTRY, LIST_GROUPS, type ListGroup } from '../schema/keys.ts';
import rawDictionary from '../field-dictionary.json' with { type: 'json' };

export const DictionarySchema = z.object({
  $comment: z.string().optional(),
  version: z.literal(1),
  groupContext: z.record(z.string(), z.string()),
  entries: z.array(
    z
      .object({
        key: z.string(),
        patterns: z.array(z.string()),
        contextPatterns: z.array(z.string()).optional(),
      })
      .refine((e) => e.patterns.length + (e.contextPatterns?.length ?? 0) > 0, {
        message: 'An entry needs at least one pattern or context pattern',
      }),
  ),
});
export type Dictionary = z.infer<typeof DictionarySchema>;

export interface CompiledEntry {
  key: string;
  /** List group for `group[].field` keys. */
  group?: ListGroup;
  patterns: RegExp[];
  contextPatterns: RegExp[];
}

export interface CompiledDictionary {
  entries: CompiledEntry[];
  groupContext: Map<ListGroup, RegExp>;
}

const word = (pattern: string) => new RegExp(`(?:^|\\s)(?:${pattern})(?=\\s|$)`, 'u');

/** Validates a dictionary against the key registry. Throws with a readable message. */
export function compileDictionary(input: unknown): CompiledDictionary {
  const dict = DictionarySchema.parse(input);
  const registryKeys = new Set(KEY_REGISTRY.map((d) => d.key));
  const seen = new Set<string>();
  for (const entry of dict.entries) {
    if (!registryKeys.has(entry.key))
      throw new Error(`Dictionary key not in registry: ${entry.key}`);
    if (seen.has(entry.key)) throw new Error(`Dictionary key listed twice: ${entry.key}`);
    seen.add(entry.key);
  }
  const missing = [...registryKeys].filter((k) => !seen.has(k));
  if (missing.length) throw new Error(`Dictionary is missing keys: ${missing.join(', ')}`);

  const groupContext = new Map<ListGroup, RegExp>();
  for (const [group, pattern] of Object.entries(dict.groupContext)) {
    if (!(group in LIST_GROUPS)) throw new Error(`Unknown list group in groupContext: ${group}`);
    groupContext.set(group as ListGroup, word(pattern));
  }

  return {
    groupContext,
    entries: dict.entries.map((e) => {
      const group = e.key.includes('[]') ? (e.key.split('[')[0] as ListGroup) : undefined;
      if (e.contextPatterns?.length && !group)
        throw new Error(`contextPatterns only apply to list keys: ${e.key}`);
      return {
        key: e.key,
        ...(group ? { group } : {}),
        patterns: e.patterns.map(word),
        contextPatterns: (e.contextPatterns ?? []).map(word),
      };
    }),
  };
}

let compiled: CompiledDictionary | null = null;

/** The built-in dictionary, compiled once. */
export function defaultDictionary(): CompiledDictionary {
  compiled ??= compileDictionary(rawDictionary);
  return compiled;
}
