// Copies packages/core/src into supabase/functions/_shared/core so Edge
// Functions (Deno) use the exact same schemas, keys and policy as the
// extension. Deno needs explicit file extensions, so relative imports are
// rewritten (`./x` → `./x.ts`, `./dir` → `./dir/index.ts`) and the field
// dictionary JSON is copied alongside.
//
//   node scripts/sync-shared.mjs          write the copy
//   node scripts/sync-shared.mjs --check  exit 1 if the copy is stale (CI)
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'packages', 'core', 'src');
const out = join(root, 'supabase', 'functions', '_shared', 'core');
const dictionarySrc = join(root, 'config', 'field-dictionary.json');
const check = process.argv.includes('--check');

const HEADER = '// GENERATED by scripts/sync-shared.mjs from packages/core/src — do not edit.\n';

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

function rewrite(file, code) {
  const fromDir = dirname(file);
  return code.replace(/(from\s+|import\s+)(['"])(\.{1,2}\/[^'"]+)\2/g, (match, kw, quote, spec) => {
    if (spec.endsWith('field-dictionary.json'))
      return `${kw}${quote}${relative(
        dirname(join(out, relative(src, file))),
        join(out, 'field-dictionary.json'),
      )
        .replace(/\\/g, '/')
        .replace(/^(?!\.)/, './')}${quote}`;
    if (/\.(ts|json)$/.test(spec)) return match;
    const target = resolve(fromDir, spec);
    if (existsSync(`${target}.ts`)) return `${kw}${quote}${spec}.ts${quote}`;
    if (existsSync(join(target, 'index.ts'))) return `${kw}${quote}${spec}/index.ts${quote}`;
    throw new Error(`Cannot resolve ${spec} from ${file}`);
  });
}

const expected = new Map();
for (const file of walk(src)) {
  if (!file.endsWith('.ts') || file.endsWith('.test.ts')) continue;
  expected.set(join(out, relative(src, file)), HEADER + rewrite(file, readFileSync(file, 'utf8')));
}
expected.set(join(out, 'field-dictionary.json'), readFileSync(dictionarySrc, 'utf8'));

if (check) {
  const actual = existsSync(out) ? walk(out) : [];
  const stale = [...expected]
    .filter(([f, c]) => !existsSync(f) || readFileSync(f, 'utf8') !== c)
    .map(([f]) => f);
  const extra = actual.filter((f) => !expected.has(f));
  if (stale.length || extra.length) {
    console.error(
      `supabase/functions/_shared/core is out of date. Run: pnpm sync:shared\n${[...stale, ...extra].map((f) => `  ${relative(root, f)}`).join('\n')}`,
    );
    process.exit(1);
  }
  console.log('Shared core copy is up to date.');
} else {
  rmSync(out, { recursive: true, force: true });
  for (const [file, content] of expected) {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content);
  }
  console.log(`Wrote ${expected.size} files to ${relative(root, out)}`);
}
