// GENERATED by scripts/sync-shared.mjs from packages/core/src — do not edit.
/** Exhaustiveness guard for discriminated unions. Throws if reached at runtime. */
export function assertNever(value: never, message = 'Unexpected value'): never {
  throw new Error(`${message}: ${JSON.stringify(value)}`);
}
